export const arsenates = [
  { elementNum:1,  occurence: 0 },
  { elementNum:2,  occurence: 0 },
  { elementNum:3,  occurence: 18 },
  { elementNum:4,  occurence: 94 },
  { elementNum:5,  occurence: 133 },
  { elementNum:6,  occurence: 60 },
  { elementNum:7,  occurence: 23 },
  { elementNum:8,  occurence: 10 },
  { elementNum:9,  occurence: 4 },
  { elementNum:10, occurence: 0 },
  { elementNum:11, occurence: 2 },
  { elementNum:12, occurence: 0 },
];
export const carbonates = [
  { elementNum:1, occurence: 0 },
  { elementNum:2, occurence: 0 },
  { elementNum:3, occurence: 13 },
  { elementNum:4, occurence: 26 },
  { elementNum:5, occurence: 30 },
  { elementNum:6, occurence: 9 },
  { elementNum:7, occurence: 5 },
  { elementNum:8, occurence: 4 },
  { elementNum:9, occurence: 0 },
  { elementNum:10,occurence: 0 },
  { elementNum:11,occurence: 1 },
  { elementNum:12,occurence: 0 },
];
export const oxides = [
  { elementNum:1, occurence: 0 },
  { elementNum:2, occurence: 38 },
  { elementNum:3, occurence: 70 },
  { elementNum:4, occurence: 50 },
  { elementNum:5, occurence: 33 },
  { elementNum:6, occurence: 10 },
  { elementNum:7, occurence: 4 },
  { elementNum:8, occurence: 4 },
  { elementNum:9, occurence: 4 },
  { elementNum:10,occurence: 2 },
  { elementNum:11,occurence: 1 },
  { elementNum:12,occurence: 1 },
];
export const silicates = [
  { elementNum: 1, occurence: 0 },
  { elementNum: 2, occurence: 1 },
  { elementNum: 3, occurence: 18 },
  { elementNum: 4, occurence: 74 },
  { elementNum: 5, occurence: 80 },
  { elementNum: 6, occurence: 49 },
  { elementNum: 7, occurence: 35 },
  { elementNum: 8, occurence: 23 },
  { elementNum: 9, occurence: 12 },
  { elementNum: 10,occurence: 9 },
  { elementNum: 11,occurence: 2 },
  { elementNum: 12,occurence: 1 },
];
export const sulfates = [
  { elementNum: 1, occurence: 0 },
  { elementNum: 2, occurence: 0 },
  { elementNum: 3, occurence: 18 },
  { elementNum: 4, occurence: 46 },
  { elementNum: 5, occurence: 58 },
  { elementNum: 6, occurence: 30 },
  { elementNum: 7, occurence: 7 },
  { elementNum: 8, occurence: 5 },
  { elementNum: 9, occurence: 0 },
  { elementNum:10, occurence: 0 },
  { elementNum:11, occurence: 0 },
  { elementNum:12, occurence: 0 },
];
